"""
API Routes for VoiceAuth
Main endpoint: POST /api/voice-detection
"""

import logging
import time
from fastapi import APIRouter, Depends, HTTPException, status

from app.api.auth import validate_api_key
from app.api.schemas import (
    VoiceDetectionRequest,
    VoiceDetectionResponse,
    ErrorResponse,
    HealthResponse
)
from app.utils.audio_processor import audio_processor
from app.models.detector import voice_detector
from app.config import settings
from app import __version__

logger = logging.getLogger(__name__)

# Create router
router = APIRouter()


@router.get(
    "/health",
    response_model=HealthResponse,
    summary="Health Check",
    description="Check API health and get supported languages"
)
async def health_check() -> HealthResponse:
    """Health check endpoint - no auth required"""
    return HealthResponse(
        status="healthy",
        version=__version__,
        supported_languages=settings.supported_languages
    )


@router.post(
    "/voice-detection",
    response_model=VoiceDetectionResponse,
    responses={
        401: {"model": ErrorResponse, "description": "Invalid or missing API key"},
        400: {"model": ErrorResponse, "description": "Invalid request format"},
        422: {"model": ErrorResponse, "description": "Validation error"},
        500: {"model": ErrorResponse, "description": "Internal server error"}
    },
    summary="Detect AI-Generated Voice",
    description=(
        "Analyze an audio sample to determine if it was generated by AI or spoken by a human. "
        "Supports Tamil, English, Hindi, Malayalam, and Telugu."
    )
)
async def detect_voice(
    request: VoiceDetectionRequest,
    api_key: str = Depends(validate_api_key)
) -> VoiceDetectionResponse:
    """
    Main voice detection endpoint
    
    Process:
    1. Validate API key (done by dependency)
    2. Decode Base64 audio
    3. Extract audio features
    4. Run detection model
    5. Return classification result
    """
    start_time = time.time()
    
    logger.info(
        f"Voice detection request received - "
        f"Language: {request.language}, Format: {request.audioFormat}"
    )
    
    try:
        # Step 1: Process audio (decode Base64, extract features)
        try:
            features = audio_processor.process_base64_audio(request.audioBase64)
            logger.info(
                f"Audio processed - Duration: {features.duration:.2f}s, "
                f"Sample rate: {features.sample_rate}Hz"
            )
        except ValueError as e:
            logger.warning(f"Audio processing failed: {str(e)}")
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail={
                    "status": "error",
                    "message": str(e)
                }
            )
        
        # Step 2: Run voice detection
        detection_result = voice_detector.detect(features, request.language)
        
        # Calculate processing time
        processing_time = time.time() - start_time
        logger.info(
            f"Detection complete in {processing_time:.2f}s - "
            f"Result: {detection_result.classification} "
            f"(confidence: {detection_result.confidence})"
        )
        
        # Step 3: Return response
        return VoiceDetectionResponse(
            status="success",
            language=request.language,
            classification=detection_result.classification,
            confidenceScore=detection_result.confidence,
            explanation=detection_result.explanation
        )
    
    except HTTPException:
        # Re-raise HTTP exceptions as-is
        raise
    
    except Exception as e:
        # Log unexpected errors
        logger.error(f"Unexpected error in voice detection: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail={
                "status": "error",
                "message": "Internal server error during voice analysis"
            }
        )


@router.get(
    "/languages",
    summary="Get Supported Languages",
    description="List all supported languages for voice detection"
)
async def get_languages():
    """Return list of supported languages"""
    return {
        "languages": settings.supported_languages,
        "count": len(settings.supported_languages)
    }
